##This Github action is used to build a new plugin snapshot.
##the actions refers to the Github action in the masterPom-plugins repo 

name: Maven Snapshot Build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    permissions:
      contents: write
      packages: write
    uses: avasis-solutions/masterPom-plugins/.github/workflows/snapshot.yml@main
    secrets: inherit
